apiVersion: v1
kind: ServiceAccount
metadata:
  name:  kubeboard
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeboard-cluster-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeboard-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeboard-cluster-role
subjects:
  - kind: ServiceAccount
    name: kubeboard
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeboard-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeboard-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeboard-role
subjects:
  - kind: ServiceAccount
    name: kubeboard
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-board
  namespace: default
spec:
  selector:
    matchLabels:
      app: kube-board
  template:
    metadata:
      labels:
        app: kube-board
    spec:
      serviceAccountName: kubeboard
      containers:
      - name: kube-board
        image: fabricioveronez/kube-board
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-board
  namespace: default
spec:
  selector:
    app: kube-board
  ports:
  - port: 3000
    nodePort: 30000
    targetPort: 3000
  type: NodePort