apiVersion: v1
kind: ServiceAccount
metadata:
  name:  kube-board
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-board-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-board-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: kube-board
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: kube-board-cluster-role
  kind: ClusterRole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-board
spec:
  selector:
    matchLabels:
      app: kube-board
  template:
    metadata:
      labels:
        app: kube-board
    spec:
      serviceAccountName: kube-board
      containers:
      - name: kube-board
        image: fabricioveronez/kube-board
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-board
spec:
  selector:
    app: kube-board
  ports:
  - port: 3000
    nodePort: 30000
    targetPort: 3000
  type: NodePort